In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fake-news-detection-datasets/News _dataset/True.csv
/kaggle/input/fake-news-detection-datasets/News _dataset/Fake.csv


In [2]:
true_data=pd.read_csv('/kaggle/input/fake-news-detection-datasets/News _dataset/True.csv')
fake_data=pd.read_csv('/kaggle/input/fake-news-detection-datasets/News _dataset/Fake.csv')

print(true_data[0:10])
fake_data[0:4]

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) -

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017

In [3]:
print(true_data['text'][0])
true_data.columns



WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support educati

Index(['title', 'text', 'subject', 'date'], dtype='object')

In [4]:
len(true_data)


21417

In [5]:
len(fake_data)

23481

In [6]:
fake_data['label'] = 1
true_data['label']=0
print(true_data.head())
fake_data.head()

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  label  
0  December 31, 2017       0  
1  December 29, 2017       0  
2  December 31, 2017       0  
3  December 30, 2017       0  
4  December 29, 2017       0  


title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  label  
0  December 31, 2017      1  
1  December 31, 2017      1  
2  December 30, 2017      1  
3  December 29, 2017      1  
4  December 25, 2017      1

In [7]:

all_data=pd.concat([fake_data, true_data])
random_permutation = np.random.permutation(len(all_data))
all_data= all_data.iloc[random_permutation]
print(all_data.columns)
all_data.head()

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')


title  \
22313  Putin Tells Obama and Western Media: “Either s...   
17315  From Haider to Strache - the FPO's march to re...   
20667  IRS CHIEF: Okay For Illegal Aliens To Use Stol...   
21715  STORE OWNER BASHES LIBERAL OBAMAITES AS HE SHU...   
19638  HUNDREDS VOTING FROM THE GRAVE In This Califor...   

                                                    text    subject  \
22313  21st Century Wire says It appears that Putin h...    US_News   
17315  VIENNA (Reuters) - Founded by former Nazis six...  worldnews   
20667  It sure would be nice to have a President and ...  left-news   
21715                                                     left-news   
19638  A comparison of records by David Goldstein, in...  left-news   

                    date  label  
22313  December 17, 2016      1  
17315  October 16, 2017       0  
20667       Apr 27, 2016      1  
21715       May 20, 2015      1  
19638       Nov 11, 2016      1

In [8]:
filterd_data=all_data.loc[:, ['title', 'text', "subject", 'label']]
filterd_data.head()

title  \
22313  Putin Tells Obama and Western Media: “Either s...   
17315  From Haider to Strache - the FPO's march to re...   
20667  IRS CHIEF: Okay For Illegal Aliens To Use Stol...   
21715  STORE OWNER BASHES LIBERAL OBAMAITES AS HE SHU...   
19638  HUNDREDS VOTING FROM THE GRAVE In This Califor...   

                                                    text    subject  label  
22313  21st Century Wire says It appears that Putin h...    US_News      1  
17315  VIENNA (Reuters) - Founded by former Nazis six...  worldnews      0  
20667  It sure would be nice to have a President and ...  left-news      1  
21715                                                     left-news      1  
19638  A comparison of records by David Goldstein, in...  left-news      1

In [9]:
filterd_data.isnull().sum()

title      0
text       0
subject    0
label      0
dtype: int64

In [10]:
filterd_data['training_feature']=filterd_data['title']+' '+filterd_data['text']+' '+filterd_data['subject']
filterd_data.head()

title  \
22313  Putin Tells Obama and Western Media: “Either s...   
17315  From Haider to Strache - the FPO's march to re...   
20667  IRS CHIEF: Okay For Illegal Aliens To Use Stol...   
21715  STORE OWNER BASHES LIBERAL OBAMAITES AS HE SHU...   
19638  HUNDREDS VOTING FROM THE GRAVE In This Califor...   

                                                    text    subject  label  \
22313  21st Century Wire says It appears that Putin h...    US_News      1   
17315  VIENNA (Reuters) - Founded by former Nazis six...  worldnews      0   
20667  It sure would be nice to have a President and ...  left-news      1   
21715                                                     left-news      1   
19638  A comparison of records by David Goldstein, in...  left-news      1   

                                        training_feature  
22313  Putin Tells Obama and Western Media: “Either s...  
17315  From Haider to Strache - the FPO's march to re...  
20667  IRS CHIEF: Okay For Illegal Aliens To Use Stol...  
21715  STORE OWNER BASHES LIBERAL OBAMAITES AS HE SHU...  
19638  HUNDREDS VOTING FROM THE GRAVE In This Califor...

In [11]:
X= filterd_data['training_feature'].values
y = filterd_data['label']


In [12]:
l_X=filterd_data['training_feature'].values[0:1000]
l_Y= filterd_data['label'].values[0:1000]

In [13]:
print(l_X.shape)
print(l_Y.shape)
type (l_X)

(1000,)
(1000,)


numpy.ndarray

In [14]:
print(X[0:1])

['Putin Tells Obama and Western Media: “Either stop talking about it or finally show some kind of proof” 21st Century Wire says It appears that Putin has had enough with being accused of tampering with the US election process this year. The Russian President s spokesman, Dmitry Peskov, pointed out that it was  indecent  of the US to accuse Russia of tampering with its election.   Remember: On Thursday evening CNN reported that Barack Obama vowed to retaliate against Russia for the  hack  that has not been verified by any independent sources nor has it provided a shred of evidence to support the claim   Tyler Durden Zero HedgePutin has had enough of the relentless barrage of US accusations that he, personally,  hacked the US presidential election. The Russian president s spokesman, Dmitry Peskov, said on Friday that the US must either stop accusing Russia of meddling in its elections or prove it. Peskov said it was  indecent  of the United States to  groundlessly  accuse Russia of inter

In [15]:
# from sklearn import preprocessing

# print(X.shape)
# print(type(X))
# # print(X[0:1])
# X=X.reshape((1,-1))
# X = preprocessing.normalize(X)
# np.random.shuffle(X)
# print(X.shape)
# print(type(X))

# X = preprocessing.normalize([X.reshape(1,-1)])


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [17]:
vectorizer= TfidfVectorizer()
X=vectorizer.fit_transform(X)

In [18]:
l_vectorizer= TfidfVectorizer()
l_X=l_vectorizer.fit_transform(l_X)

In [19]:
print(type(X))
print(X.shape)
print(type(l_X))
print(l_X.shape)


<class 'scipy.sparse._csr.csr_matrix'>
(44898, 122516)
<class 'scipy.sparse._csr.csr_matrix'>
(1000, 22629)


In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, stratify=y, random_state=42)

In [21]:
l_X_train, l_X_test, l_Y_train, l_Y_test = train_test_split(l_X, l_Y, test_size = 0.2, random_state=42)

In [22]:
X_train.shape


(35918, 122516)

In [23]:
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

In [24]:
# Model accuracy on the test set
test_y_hat=model.predict(X_test)
print(accuracy_score(test_y_hat, Y_test))

# Model Accuracy on  training set
train_y_hat = model.predict(X_train)
print(accuracy_score(train_y_hat,Y_train))

0.9905345211581291
0.9950164263043599


In [25]:
def predict(input_data):
    
    y_hat= model.predict(input_data)
    if y_hat==0:
        return "The article is Fake"
    else:
        return 'The article is not Fake'

In [26]:
print(predict(X_test[2000]))
model.predict(X_test[2000])[0]

The article is Fake


0

In [27]:
from sklearn.metrics import precision_score, recall_score, f1_score

print (precision_score(Y_train, train_y_hat,))
print (recall_score(Y_train, train_y_hat,))
print(f1_score(Y_train, train_y_hat,))


print (precision_score(Y_test, test_y_hat,))
print (recall_score(Y_test, test_y_hat,))
print(f1_score(Y_test, test_y_hat,))

0.9957898102749947
0.9946766036731435
0.9952328956829742
0.9902190091431001
0.991695059625213
0.9909564847324185


In [28]:
from sklearn.metrics import confusion_matrix
print ([['TP', 'FP'],['FN', 'TN']])
print(confusion_matrix(Y_test, test_y_hat,))
print (confusion_matrix(Y_train, train_y_hat,))

[['TP', 'FP'], ['FN', 'TN']]
[[4238   46]
 [  39 4657]]
[[17054    79]
 [  100 18685]]


In [29]:
from sklearn import svm

#Create a svm Classifier
model = svm.SVC(kernel='linear') # Linear Kernel
clf_poly=clf = svm.SVC(kernel='poly') # Polynomial kernel


In [30]:
print(X_train.shape)
# X_train.iloc[0:1000].shape



(35918, 122516)


In [31]:
#Train the model using the training sets
model.fit(l_X_train, l_Y_train)
# clf_poly.fit(X_train,Y_train)



SVC(kernel='linear')

In [32]:
#Predict the response for test dataset
y_pred = model.predict(l_X_test)

In [33]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.98
0.956989247311828
1.0
0.978021978021978
[[107   4]
 [  0  89]]


In [34]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(l_X_train, l_Y_train)



RandomForestClassifier()

In [35]:
y_pred = model.predict(l_X_test)



In [36]:
print (y_pred)

[0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 1 0 1
 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 0 1
 0 0 1 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 1 1
 1 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 0 0 0
 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0]


In [37]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,confusion_matrix


print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.98
0.967032967032967
0.9887640449438202
0.9777777777777779
[[108   3]
 [  1  88]]


In [38]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()


In [39]:
# X_train.todense()
# model2=GaussianNB()
# model2.fit(X_train.toarray(), Y_train)

In [40]:
y_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0])

In [41]:
model.fit(l_X_train.toarray(), l_Y_train)


GaussianNB()

In [42]:
y_pred = model.predict(l_X_test.toarray())


In [43]:
print(accuracy_score(y_pred, l_Y_test))
print (precision_score(l_Y_test, y_pred,))
print (recall_score(l_Y_test, y_pred,))
print(f1_score(l_Y_test, y_pred,))
print(confusion_matrix(l_Y_test, y_pred,))


0.755
0.6818181818181818
0.8426966292134831
0.7537688442211055
[[76 35]
 [14 75]]
